// src/lib/invoices.ts
// PDF invoice generation helpers (server-side only)

import { PDFDocument, StandardFonts } from 'pdf-lib'

export type InvoiceSnapshot = {
  invoice_number: string
  issued_at: string // ISO
  gym: {
    name: string
    city?: string
    country?: string
  }
  member: {
    user_id: string
    member_code?: string | null
    first_name?: string | null
    last_name?: string | null
    email?: string | null
    joined_at?: string | null
  }
  transaction: {
    subscription_id: string
    subscription_type: string
    plan: string
    start_date: string | null
    end_date: string | null
    sessions_total: number | null
    amount: number
    currency: string
    paid_at: string
  }
}

export function makeInvoiceNumber(input?: { paidAtISO?: string; subscriptionId?: string }) {
  const d = input?.paidAtISO ? new Date(input.paidAtISO) : new Date()
  const y = d.getUTCFullYear()
  const m = String(d.getUTCMonth() + 1).padStart(2, '0')
  const day = String(d.getUTCDate()).padStart(2, '0')
  const suffix = (input?.subscriptionId || crypto.randomUUID()).replace(/[^a-f0-9]/gi, '').slice(0, 6).toUpperCase()
  return `INV-${y}${m}${day}-${suffix}`
}

function money(amount: number, currency: string) {
  const safe = Number.isFinite(amount) ? amount : 0
  try {
    // Use en-GB for consistent formatting
    return new Intl.NumberFormat('en-GB', {
      style: 'currency',
      currency,
      maximumFractionDigits: 0,
    }).format(safe)
  } catch {
    return `${safe} ${currency}`
  }
}

function fmtDate(iso: string) {
  const dt = new Date(iso)
  if (Number.isNaN(dt.getTime())) return iso
  return dt.toLocaleDateString('en-GB', { year: 'numeric', month: 'short', day: '2-digit' })
}

function safeText(v: any) {
  const s = v === null || v === undefined ? '' : String(v)
  return s
}

export async function generateInvoicePdfBytes(snapshot: InvoiceSnapshot) {
  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([595.28, 841.89]) // A4 (pt)

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const { width, height } = page.getSize()
  const margin = 48

  const drawText = (text: string, x: number, y: number, size = 11, bold = false) => {
    page.drawText(text, {
      x,
      y,
      size,
      font: bold ? fontBold : font,
    })
  }

  // Header
  drawText(snapshot.gym.name || 'ATOM', margin, height - margin - 8, 20, true)
  drawText('INVOICE', width - margin - 90, height - margin - 2, 16, true)

  // Meta
  const metaTop = height - margin - 44
  drawText(`Invoice #: ${snapshot.invoice_number}`, margin, metaTop, 11, true)
  drawText(`Issued: ${fmtDate(snapshot.issued_at)}`, margin, metaTop - 16, 11)

  // Bill to
  const billTop = metaTop - 48
  drawText('Bill To', margin, billTop, 12, true)

  const fullName = [snapshot.member.first_name ?? '', snapshot.member.last_name ?? ''].join(' ').trim()
  const memberLine = fullName || snapshot.member.email || snapshot.member.user_id
  drawText(memberLine, margin, billTop - 18, 11)
  if (snapshot.member.member_code) {
    drawText(`Member ID: ${snapshot.member.member_code}`, margin, billTop - 34, 10)
  }
  if (snapshot.member.joined_at) {
    drawText(`First joined: ${fmtDate(snapshot.member.joined_at)}`, margin, billTop - 48, 10)
  }

  // Transaction details
  const boxTop = billTop - 88
  drawText('Transaction', margin, boxTop, 12, true)

  const leftX = margin
  const rightX = width / 2 + 10
  let y = boxTop - 18

  const row = (label: string, value: string, col: 'left' | 'right' = 'left') => {
    const x = col === 'left' ? leftX : rightX
    drawText(label, x, y, 10, true)
    drawText(value, x + 120, y, 10)
  }

  row('Plan:', safeText(snapshot.transaction.plan), 'left')
  row('Type:', safeText(snapshot.transaction.subscription_type), 'right')
  y -= 16
  row('Paid at:', fmtDate(snapshot.transaction.paid_at), 'left')
  row('Amount:', money(snapshot.transaction.amount, snapshot.transaction.currency), 'right')
  y -= 16
  row('Start:', snapshot.transaction.start_date ? fmtDate(snapshot.transaction.start_date) : '—', 'left')
  row('End:', snapshot.transaction.end_date ? fmtDate(snapshot.transaction.end_date) : '—', 'right')

  y -= 16
  if (snapshot.transaction.sessions_total !== null && snapshot.transaction.sessions_total !== undefined) {
    row('Sessions:', String(snapshot.transaction.sessions_total), 'left')
  }
  row('Subscription ID:', snapshot.transaction.subscription_id, 'right')

  // Footer
  const footer = `Generated by ATOM App · ${snapshot.gym.city ? snapshot.gym.city + ', ' : ''}${snapshot.gym.country ?? ''}`.trim()
  drawText(footer, margin, margin - 10, 9)

  const bytes = await pdfDoc.save()
  return bytes
}
